#!/bin/bash
# Script to run devcontainer feature tests locally
# Requires: @devcontainers/cli (npm install -g @devcontainers/cli)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
FEATURE=""
BASE_IMAGE=""
SKIP_SCENARIOS=false
SKIP_AUTOGENERATED=false

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Run devcontainer feature tests locally."
    echo ""
    echo "Options:"
    echo "  -f, --feature <name>     Feature to test (e.g., 'bun'). If not specified, tests all features."
    echo "  -i, --image <image>      Base image to test against (e.g., 'mcr.microsoft.com/devcontainers/base:ubuntu')"
    echo "  --skip-scenarios         Skip scenario tests"
    echo "  --skip-autogenerated     Skip autogenerated tests"
    echo "  -h, --help               Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                                    # Run all tests for all features"
    echo "  $0 -f bun                             # Run all tests for 'bun' feature"
    echo "  $0 -f bun -i ubuntu:latest            # Test 'bun' feature on ubuntu:latest"
    echo "  $0 -f bun --skip-scenarios            # Run only autogenerated tests"
    echo ""
}

# Check if devcontainer CLI is installed
check_cli() {
    if ! command -v devcontainer &> /dev/null; then
        echo -e "${RED}Error: devcontainer CLI is not installed.${NC}"
        echo ""
        echo "Install it with:"
        echo "  npm install -g @devcontainers/cli"
        echo ""
        exit 1
    fi
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -f|--feature)
            FEATURE="$2"
            shift 2
            ;;
        -i|--image)
            BASE_IMAGE="$2"
            shift 2
            ;;
        --skip-scenarios)
            SKIP_SCENARIOS=true
            shift
            ;;
        --skip-autogenerated)
            SKIP_AUTOGENERATED=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            usage
            exit 1
            ;;
    esac
done

check_cli

echo -e "${GREEN}Running devcontainer feature tests...${NC}"
echo ""

# Build the command
CMD="devcontainer features test"

if [ -n "$FEATURE" ]; then
    CMD="$CMD -f $FEATURE"
fi

if [ -n "$BASE_IMAGE" ]; then
    CMD="$CMD -i $BASE_IMAGE"
fi

if [ "$SKIP_SCENARIOS" = true ]; then
    CMD="$CMD --skip-scenarios"
fi

if [ "$SKIP_AUTOGENERATED" = true ]; then
    CMD="$CMD --skip-autogenerated"
fi

# Add the project root
CMD="$CMD $SCRIPT_DIR"

echo -e "${YELLOW}Executing: $CMD${NC}"
echo ""

# Run the tests
$CMD
